//! Desktop presentation builder for planner events.
//!
//! Turns the shared [`takusu_agent::presentation::Presentation`] events into a
//! desktop-friendly payload (title, body, action buttons) and mints
//! server-issued one-shot capabilities for the immediate quick actions.

use takusu_agent::capability::{ActionCapability, CapabilityRequest, InputPath};
use takusu_agent::presentation::{Action, ActionKind, WorkState};
#[cfg(test)]
use takusu_agent::presentation::{CheckInCard, TaskCard};
use takusu_agent::{Presentation, SurfaceCommand};
use takusu_contracts::EventLedgerRow;

use crate::notify::{DesktopNotification, NotificationAction};
use crate::state::{DesktopError, DesktopState};
use crate::transport::DesktopTransport;

/// Execute a desktop quick action, using an existing capability when available,
/// minting a new screen capability on demand, or opening the surface panel.
pub async fn execute_quick_action(
    transport: &dyn DesktopTransport,
    desktop_state: Option<&DesktopState>,
    action: &DesktopAction,
) -> Result<Presentation, DesktopError> {
    match action.kind {
        ActionKind::Panel => {
            let response = transport.send_command(SurfaceCommand::OpenPanel).await?;
            if !response.accepted {
                tracing::warn!(
                    command = ?SurfaceCommand::OpenPanel,
                    reason = ?response.reason,
                    "panel command not accepted"
                );
            } else if let Some(state) = desktop_state {
                // Keep the compact panel visible even if the surface is idle, so
                // the user can interact with the current presentation.
                state.set_panel_open(true);
            }
            return Ok(Presentation::Text {
                text: "panel opened".into(),
            });
        }
        ActionKind::Approval => {
            let response = transport.send_command(SurfaceCommand::OpenApproval).await?;
            if !response.accepted {
                tracing::warn!(
                    command = ?SurfaceCommand::OpenApproval,
                    reason = ?response.reason,
                    "approval command not accepted"
                );
            } else if let Some(state) = desktop_state {
                // Approval surfaces are shown by state, but ensure the panel is
                // requested in case it was hidden.
                state.set_panel_open(true);
            }
            return Ok(Presentation::Text {
                text: "approval opened".into(),
            });
        }
        ActionKind::Immediate => {}
    }

    if let Some(cap) = &action.capability {
        return transport.authorize_action(cap, None).await;
    }

    if let (Some(task_id), Some(action_name)) =
        (action.task_id.as_deref(), action.action.as_deref())
    {
        let request = CapabilityRequest {
            task_id: task_id.into(),
            action: action_name.into(),
            device_id: "desktop".into(),
            input_path: Some(InputPath::ScreenCapability),
            event_id: action.event_id.clone(),
            snooze_minutes: action.snooze_minutes,
            ..Default::default()
        };
        return transport.quick_action(&request).await;
    }

    Ok(Presentation::Text {
        text: format!("No capability for {}", action.label),
    })
}

/// One actionable button on a desktop notification or compact panel.
#[derive(Debug, Clone)]
pub struct DesktopAction {
    pub id: String,
    pub label: String,
    pub kind: ActionKind,
    /// Server-issued one-shot capability, present when the action can be
    /// authorized directly.
    pub capability: Option<ActionCapability>,
    /// Quick-action parameters for capabilities that must be minted on demand
    /// (e.g. the current-task card generated by the desktop).
    pub task_id: Option<String>,
    pub action: Option<String>,
    pub snooze_minutes: Option<i64>,
    /// Source event id, passed through to the capability when minted on demand.
    pub event_id: Option<String>,
}

impl DesktopAction {
    fn from_agent(action: &Action) -> Self {
        Self {
            id: action.id.clone(),
            label: action.label.clone(),
            kind: action.kind,
            capability: action.capability.clone(),
            task_id: None,
            action: None,
            snooze_minutes: None,
            event_id: None,
        }
    }

    /// Returns `true` if this action can be invoked without an extra mint step.
    pub fn is_ready(&self) -> bool {
        self.capability.is_some() || (self.action.is_some() && self.task_id.is_some())
    }
}

impl Default for DesktopAction {
    fn default() -> Self {
        Self {
            id: String::new(),
            label: String::new(),
            kind: ActionKind::Immediate,
            capability: None,
            task_id: None,
            action: None,
            snooze_minutes: None,
            event_id: None,
        }
    }
}

/// Infer the quick-action name from an action label heuristically.
///
/// The server may return unminted `Immediate` actions with localized labels;
/// the desktop fills in the `action` field so `execute_quick_action` can mint
/// a capability on demand without changing the shared planner format.
fn infer_quick_action(label: &str) -> Option<&'static str> {
    let lower = label.to_lowercase();
    if lower.contains("開始") || lower.contains("start") {
        return Some("start");
    }
    if lower.contains("一時停止") || lower.contains("停止") || lower.contains("pause") {
        return Some("pause");
    }
    if lower.contains("完了") || lower.contains("complete") {
        return Some("complete");
    }
    if lower.contains("ずらす")
        || lower.contains("10分")
        || lower.contains("delay")
        || lower.contains("あと")
    {
        return Some("delay");
    }
    None
}

/// Populate `task_id` and `action` on an unminted `Immediate` action.
fn set_unminted_quick_action(da: &mut DesktopAction, task_id: Option<&str>, label: &str) {
    if da.kind != ActionKind::Immediate
        || da.capability.is_some()
        || da.task_id.is_some()
        || da.action.is_some()
    {
        return;
    }
    if let (Some(task_id), Some(action)) = (task_id, infer_quick_action(label)) {
        da.task_id = Some(task_id.into());
        da.action = Some(action.into());
    }
}

/// A desktop-friendly rendering of a planner `Presentation`.
#[derive(Debug, Clone)]
pub struct DesktopPresentation {
    pub title: String,
    pub body: String,
    pub actions: Vec<DesktopAction>,
    /// The original presentation so callers can render richer views.
    pub presentation: Presentation,
    pub task_id: Option<String>,
    pub event_id: Option<String>,
}

impl DesktopPresentation {
    /// The first quick action whose label matches `label`, if any.
    pub fn action_by_label(&self, label: &str) -> Option<&DesktopAction> {
        self.actions.iter().find(|a| a.label == label)
    }
}

impl Default for DesktopPresentation {
    fn default() -> Self {
        Self {
            title: String::new(),
            body: String::new(),
            actions: Vec::new(),
            presentation: Presentation::Text {
                text: String::new(),
            },
            task_id: None,
            event_id: None,
        }
    }
}

/// Convert a desktop presentation into a D-Bus notification payload.
pub fn presentation_to_notification(presentation: &DesktopPresentation) -> DesktopNotification {
    DesktopNotification {
        id: 0,
        title: presentation.title.clone(),
        body: presentation.body.clone(),
        actions: presentation
            .actions
            .iter()
            .map(|a| NotificationAction {
                key: a.id.clone(),
                label: a.label.clone(),
                kind: a.kind,
                capability: a.capability.clone(),
            })
            .collect(),
    }
}

/// Build a desktop presentation from a planner ledger row, minting action
/// capabilities for the immediate quick actions the user can tap.
#[allow(clippy::collapsible_if)]
pub async fn build_presentation(
    transport: &dyn DesktopTransport,
    event: &EventLedgerRow,
    device_id: &str,
) -> Result<DesktopPresentation, DesktopError> {
    let presentation: Presentation = serde_json::from_str(&event.presentation)
        .map_err(|error| DesktopError::Transport(format!("invalid event presentation: {error}")))?;

    let mut desktop = DesktopPresentation {
        title: "takusu".into(),
        body: presentation.voice_template(),
        actions: Vec::new(),
        presentation,
        task_id: event.task_id.clone(),
        event_id: Some(event.id.clone()),
    };

    match &desktop.presentation {
        Presentation::CheckIn(card) => {
            let kind = event.kind.as_str();
            for action in card.act.actions.as_slice() {
                let mut da = DesktopAction::from_agent(action);
                set_unminted_quick_action(&mut da, event.task_id.as_deref(), &action.label);
                if action.kind == ActionKind::Immediate
                    && matches!(kind, "task_start_time_reached" | "task_non_start_continued")
                {
                    if let Some(task_id) = &event.task_id {
                        match mint_capability(
                            transport,
                            task_id,
                            "start",
                            device_id,
                            Some(event.id.clone()),
                            None,
                        )
                        .await
                        {
                            Ok(cap) => da.capability = Some(cap),
                            Err(error) => {
                                tracing::warn!(error = %error, "failed to mint start capability");
                            }
                        }
                    }
                }
                desktop.actions.push(da);
            }
            for action in card.shift.actions.as_slice() {
                let mut da = DesktopAction::from_agent(action);
                set_unminted_quick_action(&mut da, event.task_id.as_deref(), &action.label);
                if action.kind == ActionKind::Immediate
                    && matches!(kind, "task_start_time_reached" | "task_non_start_continued")
                    && (action.label.contains("10分") || action.label.contains("ずらす"))
                {
                    if let Some(task_id) = &event.task_id {
                        match mint_capability(
                            transport,
                            task_id,
                            "delay",
                            device_id,
                            Some(event.id.clone()),
                            Some(10),
                        )
                        .await
                        {
                            Ok(cap) => da.capability = Some(cap),
                            Err(error) => {
                                tracing::warn!(error = %error, "failed to mint delay capability");
                            }
                        }
                    }
                }
                desktop.actions.push(da);
            }
        }
        Presentation::CurrentTask(card) => {
            desktop.title = card.title.clone();
            if let Some(settlement) = &card.settlement {
                desktop.body = format!(
                    "{} どうしますか。行動するか、ずらすかを選んでください",
                    settlement.question
                );
                for action in settlement.act.actions.as_slice() {
                    let mut da = DesktopAction::from_agent(action);
                    set_unminted_quick_action(&mut da, event.task_id.as_deref(), &action.label);
                    desktop.actions.push(da);
                }
                for action in settlement.shift.actions.as_slice() {
                    let mut da = DesktopAction::from_agent(action);
                    set_unminted_quick_action(&mut da, event.task_id.as_deref(), &action.label);
                    desktop.actions.push(da);
                }
            } else if let Some(task_id) = &event.task_id {
                desktop.actions = current_task_quick_actions(card.work_state, task_id, device_id);
                // Mint capabilities for the on-demand quick actions.
                for action in &mut desktop.actions {
                    if let (Some(task), Some(action_name)) =
                        (action.task_id.as_deref(), action.action.as_deref())
                    {
                        match mint_capability(
                            transport,
                            task,
                            action_name,
                            device_id,
                            Some(event.id.clone()),
                            action.snooze_minutes,
                        )
                        .await
                        {
                            Ok(cap) => action.capability = Some(cap),
                            Err(error) => {
                                tracing::warn!(
                                    error = %error,
                                    action = action_name,
                                    "failed to mint current-task capability"
                                );
                            }
                        }
                    }
                }
            }
        }
        Presentation::ScheduleAlert(alert) => {
            desktop.title = "takusu".into();
            desktop.body = alert.message.clone();
        }
        _ => {}
    }

    if let Some(event_id) = &desktop.event_id {
        for action in &mut desktop.actions {
            if action.event_id.is_none() {
                action.event_id = Some(event_id.clone());
            }
        }
    }

    Ok(desktop)
}

/// Build a desktop notification from a raw `Presentation`. This is a
/// convenience for callers that already have a presentation and do not need
/// server-issued capabilities (e.g. surface-state fallback notifications).
pub fn build_presentation_from_presentation(
    presentation: &Presentation,
    task_id: Option<&str>,
    event_id: Option<&str>,
) -> DesktopPresentation {
    let mut desktop = DesktopPresentation {
        title: "takusu".into(),
        body: presentation.voice_template(),
        actions: Vec::new(),
        presentation: presentation.clone(),
        task_id: task_id.map(Into::into),
        event_id: event_id.map(Into::into),
    };

    match presentation {
        Presentation::CheckIn(card) => {
            for action in card.act.actions.as_slice() {
                let mut da = DesktopAction::from_agent(action);
                set_unminted_quick_action(&mut da, desktop.task_id.as_deref(), &action.label);
                desktop.actions.push(da);
            }
            for action in card.shift.actions.as_slice() {
                let mut da = DesktopAction::from_agent(action);
                set_unminted_quick_action(&mut da, desktop.task_id.as_deref(), &action.label);
                desktop.actions.push(da);
            }
        }
        Presentation::CurrentTask(card) => {
            desktop.title = card.title.clone();
            if let Some(settlement) = &card.settlement {
                desktop.body = format!(
                    "{} どうしますか。行動するか、ずらすかを選んでください",
                    settlement.question
                );
                for action in settlement.act.actions.as_slice() {
                    let mut da = DesktopAction::from_agent(action);
                    set_unminted_quick_action(&mut da, desktop.task_id.as_deref(), &action.label);
                    desktop.actions.push(da);
                }
                for action in settlement.shift.actions.as_slice() {
                    let mut da = DesktopAction::from_agent(action);
                    set_unminted_quick_action(&mut da, desktop.task_id.as_deref(), &action.label);
                    desktop.actions.push(da);
                }
            } else if let Some(task_id) = desktop.task_id.as_deref() {
                desktop.actions = current_task_quick_actions(card.work_state, task_id, "desktop");
            }
        }
        Presentation::ScheduleAlert(alert) => {
            desktop.body = alert.message.clone();
        }
        _ => {}
    }

    if let Some(event_id) = &desktop.event_id {
        for action in &mut desktop.actions {
            if action.event_id.is_none() {
                action.event_id = Some(event_id.clone());
            }
        }
    }

    desktop
}

fn current_task_quick_actions(
    work_state: WorkState,
    task_id: &str,
    _device_id: &str,
) -> Vec<DesktopAction> {
    // The toggle between start and pause follows the shared work state.
    let (toggle_label, toggle_action) = match work_state {
        WorkState::InProgress => ("一時停止", "pause"),
        _ => ("開始", "start"),
    };

    let mut actions = vec![
        DesktopAction {
            id: "start-pause".into(),
            label: toggle_label.into(),
            kind: ActionKind::Immediate,
            capability: None,
            task_id: Some(task_id.into()),
            action: Some(toggle_action.into()),
            snooze_minutes: None,
            event_id: None,
        },
        DesktopAction {
            id: "complete".into(),
            label: "完了".into(),
            kind: ActionKind::Immediate,
            capability: None,
            task_id: Some(task_id.into()),
            action: Some("complete".into()),
            snooze_minutes: None,
            event_id: None,
        },
        DesktopAction {
            id: "dismiss".into(),
            label: "10分ずらす".into(),
            kind: ActionKind::Immediate,
            capability: None,
            task_id: Some(task_id.into()),
            action: Some("delay".into()),
            snooze_minutes: Some(10),
            event_id: None,
        },
    ];

    // Overdue or not-started tasks can also be explicitly started; in-progress
    // tasks can also be paused. Add the opposite action so every state exposes
    // the full start/pause/complete/dismiss set, leaving the server to reject
    // the invalid one with its normal state check.
    match work_state {
        WorkState::InProgress => {
            actions.push(DesktopAction {
                id: "start".into(),
                label: "開始".into(),
                kind: ActionKind::Immediate,
                capability: None,
                task_id: Some(task_id.into()),
                action: Some("start".into()),
                snooze_minutes: None,
                event_id: None,
            });
        }
        WorkState::NotStarted | WorkState::Overdue => {
            actions.push(DesktopAction {
                id: "pause".into(),
                label: "一時停止".into(),
                kind: ActionKind::Immediate,
                capability: None,
                task_id: Some(task_id.into()),
                action: Some("pause".into()),
                snooze_minutes: None,
                event_id: None,
            });
        }
    }

    actions
}

async fn mint_capability(
    transport: &dyn DesktopTransport,
    task_id: &str,
    action: &str,
    device_id: &str,
    event_id: Option<String>,
    snooze_minutes: Option<i64>,
) -> Result<ActionCapability, DesktopError> {
    transport
        .mint_action_capability(&CapabilityRequest {
            task_id: task_id.into(),
            action: action.into(),
            device_id: device_id.into(),
            input_path: Some(InputPath::NotificationCapability),
            event_id,
            snooze_minutes,
            ..Default::default()
        })
        .await
}

#[cfg(test)]
mod tests {
    use super::*;
    use takusu_agent::presentation::{Action, ActionGroup, TaskAuthority};
    use takusu_agent::surface::SurfaceStateMachine;
    use takusu_contracts::EventDeliveryState;

    use crate::transport::MockTransport;

    fn check_in_event() -> EventLedgerRow {
        let card = CheckInCard::new(
            "「テスト」の開始時刻です",
            ActionGroup::new(
                "行動",
                vec![Action {
                    id: "act".into(),
                    label: "着手".into(),
                    kind: ActionKind::Immediate,
                    capability: None,
                }],
            )
            .unwrap(),
            ActionGroup::new(
                "ズラす",
                vec![Action {
                    id: "shift".into(),
                    label: "10分後にずらす".into(),
                    kind: ActionKind::Immediate,
                    capability: None,
                }],
            )
            .unwrap(),
        )
        .unwrap();
        EventLedgerRow {
            id: "event-1".into(),
            kind: "task_start_time_reached".into(),
            task_id: Some("task-1".into()),
            presentation: serde_json::to_string(&Presentation::CheckIn(card)).unwrap(),
            urgency: "normal".into(),
            schedule_revision: 1,
            distribution_revision: None,
            observation_kind: "start-time".into(),
            delivery_state: EventDeliveryState::PendingDelivery,
            created_at: takusu_types::Timestamp::from_second(0).unwrap(),
            delivered_at: None,
        }
    }

    fn current_task_event() -> EventLedgerRow {
        let card = TaskCard {
            title: "テスト".into(),
            reference: "#1".into(),
            start_at: None,
            end_at: None,
            work_state: WorkState::NotStarted,
            authority: TaskAuthority::Candidate,
            next_task: None,
            settlement: None,
        };
        EventLedgerRow {
            id: "event-2".into(),
            kind: "current_task".into(),
            task_id: Some("task-1".into()),
            presentation: serde_json::to_string(&Presentation::CurrentTask(card)).unwrap(),
            urgency: "normal".into(),
            schedule_revision: 1,
            distribution_revision: None,
            observation_kind: "current".into(),
            delivery_state: EventDeliveryState::PendingDelivery,
            created_at: takusu_types::Timestamp::from_second(0).unwrap(),
            delivered_at: None,
        }
    }

    #[tokio::test]
    async fn build_check_in_mints_start_capability() {
        let transport = MockTransport::new(SurfaceStateMachine::new().snapshot());
        let event = check_in_event();
        let desktop = build_presentation(&transport, &event, "desktop")
            .await
            .unwrap();

        assert_eq!(desktop.title, "takusu");
        assert!(!desktop.body.is_empty());
        assert!(
            desktop
                .actions
                .iter()
                .any(|a| a.label == "着手" && a.capability.is_some())
        );
    }

    #[tokio::test]
    async fn build_current_task_mints_quick_action_capabilities() {
        let transport = MockTransport::new(SurfaceStateMachine::new().snapshot());
        let event = current_task_event();
        let desktop = build_presentation(&transport, &event, "desktop")
            .await
            .unwrap();

        assert_eq!(desktop.title, "テスト");
        assert!(!desktop.actions.is_empty());
        let start = desktop
            .actions
            .iter()
            .find(|a| a.label == "開始")
            .expect("start action");
        assert!(start.capability.is_some());
    }

    #[test]
    fn presentation_to_notification_maps_body_and_actions() {
        let desktop = DesktopPresentation {
            title: "takusu".into(),
            body: "body".into(),
            actions: vec![DesktopAction {
                id: "act".into(),
                label: "着手".into(),
                kind: ActionKind::Immediate,
                capability: None,
                task_id: None,
                action: None,
                snooze_minutes: None,
                event_id: None,
            }],
            presentation: Presentation::Text {
                text: "body".into(),
            },
            task_id: None,
            event_id: None,
        };
        let notification = presentation_to_notification(&desktop);
        assert_eq!(notification.title, "takusu");
        assert_eq!(notification.body, "body");
        assert_eq!(notification.actions.len(), 1);
        assert_eq!(notification.actions[0].label, "着手");
    }

    #[test]
    fn work_state_determines_start_pause_toggle() {
        let not_started = current_task_quick_actions(WorkState::NotStarted, "t-1", "desktop");
        assert!(
            not_started
                .iter()
                .any(|a| a.label == "開始" && a.action.as_deref() == Some("start"))
        );

        let in_progress = current_task_quick_actions(WorkState::InProgress, "t-1", "desktop");
        assert!(
            in_progress
                .iter()
                .any(|a| a.label == "一時停止" && a.action.as_deref() == Some("pause"))
        );
    }
}
