[package]
name = "takusu-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
sqlx = ["dep:sqlx", "takusu-types/sqlx"]

[dependencies]
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
thiserror.workspace = true
sqlx = { version = "0.9", default-features = false, features = ["derive", "macros"], optional = true }
takusu-types = { workspace = true }
takusu-search.workspace = true

