//! Shared enum foundation for type-safe label handling across crates.
//!
//! Many `takusu` crates (`takusu-storage`, `takusu-client`, `takusu-worker`) model
//! the same fixed-vocabulary fields (`status`, `window_mode`, `scope`, ...) as
//! `String`. This module provides:
//!
//! - [`EnumLabel`]: a trait unifying `Display` / `FromStr` / `Default` so that
//!   enum values can be round-tripped through DB columns and JSON.
//! - [`enum_serde`]: a serde adapter usable via `#[serde(with = "takusu_util::enum_serde")]`.
//! - [`enum_label!`]: a macro generating `Display` / `FromStr` / `TryFrom<String>`
//!   / `Default` / `EnumLabel` for enum definitions in one shot.
//! - [`UnknownLabel`]: the error returned when a string does not match any
//!   variant.
//!
//! Design constraints (see `doc/type-safety-issues.md` §8.2):
//!
//! - `takusu-storage` enables sqlx with `default-features = false` and no
//!   driver, so we cannot implement `Type`/`Encode`/`Decode` here. Callers use
//!   `#[sqlx(try_from = "String")]` instead, which only requires `TryFrom<String>`.
//! - `takusu-util` is the only shared crate that the storage/client/worker trio
//!   all depend on and that builds for wasm, so this is the single place to
//!   host these definitions.

use thiserror::Error;

/// Error returned when a string does not correspond to any enum variant.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
#[error("unknown {enum_name} label: {value:?}")]
pub struct UnknownLabel {
    enum_name: &'static str,
    value: String,
}

impl UnknownLabel {
    /// Construct a new `UnknownLabel` error.
    ///
    /// `enum_name` should be the Rust type name (typically `stringify!(...)`
    /// of the enum) and `value` is the offending string.
    pub fn new(enum_name: &'static str, value: impl Into<String>) -> Self {
        Self {
            enum_name,
            value: value.into(),
        }
    }

    /// The Rust type name passed to [`UnknownLabel::new`].
    pub fn enum_name(&self) -> &'static str {
        self.enum_name
    }

    /// The string that did not match any variant.
    pub fn value(&self) -> &str {
        &self.value
    }
}

/// Unify enum handling across DB / JSON / string boundaries.
///
/// Implementations are normally generated by the [`enum_label!`](crate::enum_label!)
/// macro. The supertrait set ensures the value can be:
///
/// - printed and parsed as a string (`Display` + `FromStr`),
/// - stored in a sqlx `FromRow` struct via `#[sqlx(try_from = "String")]`
///   (`TryFrom<String>` is provided by the macro),
/// - used as a default value: the macro also derives `std::default::Default`,
///   and [`EnumLabel::enum_default`] is provided as an explicit method that
///   returns the same variant as `Default::default()` but without the
///   method-resolution ambiguity that `Default::default()` can cause in generic
///   contexts.
pub trait EnumLabel:
    Sized
    + Clone
    + Copy
    + PartialEq
    + Eq
    + std::fmt::Display
    + std::str::FromStr
    + Send
    + Sync
    + 'static
{
    /// Fallback used when a DB column is NULL or holds an unknown value.
    ///
    /// Distinct from `Default::default()` to avoid method-resolution ambiguity.
    fn enum_default() -> Self;

    /// All variants, in declaration order. Useful for error messages and
    /// API-side validation.
    fn all_variants() -> &'static [Self];

    /// The string label for this variant. Equivalent to `to_string()` but
    /// returns a `&'static str` so it can be used in contexts that need one.
    fn as_str(&self) -> &'static str;
}

/// Serde adapter for [`EnumLabel`] types.
///
/// Use with `#[serde(with = "takusu_util::enum_serde")]`. The value is
/// serialized as its `Display` string and deserialized via `FromStr`, so the
/// JSON representation stays a plain string.
pub mod enum_serde {
    use super::EnumLabel;
    use serde::{Deserialize, Deserializer, Serializer};

    /// Serialize an [`EnumLabel`] value as its `Display` string.
    pub fn serialize<S, T>(value: &T, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
        T: EnumLabel,
    {
        serializer.collect_str(value)
    }

    /// Deserialize an [`EnumLabel`] value from a string via `FromStr`.
    pub fn deserialize<'de, D, T>(deserializer: D) -> Result<T, D::Error>
    where
        D: Deserializer<'de>,
        T: EnumLabel,
        <T as std::str::FromStr>::Err: std::fmt::Display,
    {
        let s = String::deserialize(deserializer)?;
        s.parse().map_err(serde::de::Error::custom)
    }

    /// Serde adapter for `Option<EnumLabel>` fields.
    ///
    /// Use with `#[serde(with = "takusu_util::enum_serde::option")]` on
    /// `Option<SomeEnum>` fields. `None` is serialized as a missing/null
    /// value; `Some(value)` is serialized as the enum's `Display` string.
    pub mod option {
        use super::EnumLabel;
        use serde::{Deserialize, Deserializer, Serializer};

        /// Serialize an `Option<EnumLabel>` value.
        pub fn serialize<S, T>(value: &Option<T>, serializer: S) -> Result<S::Ok, S::Error>
        where
            S: Serializer,
            T: EnumLabel,
        {
            match value {
                Some(v) => super::serialize(v, serializer),
                None => serializer.serialize_none(),
            }
        }

        /// Deserialize an `Option<EnumLabel>` value from an optional string.
        pub fn deserialize<'de, D, T>(deserializer: D) -> Result<Option<T>, D::Error>
        where
            D: Deserializer<'de>,
            T: EnumLabel,
            <T as std::str::FromStr>::Err: std::fmt::Display,
        {
            let opt = Option::<String>::deserialize(deserializer)?;
            match opt {
                Some(s) => s.parse().map(Some).map_err(serde::de::Error::custom),
                None => Ok(None),
            }
        }
    }
}

/// Generate `Display` / `FromStr` / `TryFrom<String>` / `Default` / [`EnumLabel`]
/// for a string-backed enum.
///
/// # Example
///
/// ```
/// use takusu_util::{enum_label, EnumLabel};
///
/// enum_label! {
///     pub enum TaskStatus {
///         #[default] Pending = "pending",
///         Scheduled = "scheduled",
///         Completed = "completed",
///     }
/// }
///
/// assert_eq!(TaskStatus::Pending.to_string(), "pending");
/// assert_eq!("scheduled".parse::<TaskStatus>().unwrap(), TaskStatus::Scheduled);
/// assert_eq!(TaskStatus::default(), TaskStatus::Pending);
/// assert_eq!(TaskStatus::enum_default(), TaskStatus::Pending);
/// assert_eq!(TaskStatus::all_variants().len(), 3);
/// ```
///
/// # Variant syntax
///
/// The first variant **must** be annotated with `#[default]`. It becomes both
/// `Default::default()` and [`EnumLabel::enum_default`]. Each subsequent variant
/// is assigned a string label via `Variant = "label"`. The macro generates a
/// `TryFrom<String>` implementation that delegates to `FromStr`, so the result
/// can be used with `#[sqlx(try_from = "String")]`.
#[macro_export]
macro_rules! enum_label {
    (
        $(#[$meta:meta])*
        $vis:vis enum $name:ident {
            #[default] $first:ident = $first_s:literal,
            $($variant:ident = $s:literal),* $(,)?
        }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
        $vis enum $name {
            #[serde(rename = $first_s)]
            $first,
            $(
                #[serde(rename = $s)]
                $variant
            ),*
        }

        impl std::fmt::Display for $name {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str(match self {
                    Self::$first => $first_s,
                    $(Self::$variant => $s),*
                })
            }
        }

        impl std::str::FromStr for $name {
            type Err = $crate::UnknownLabel;
            fn from_str(s: &str) -> Result<Self, Self::Err> {
                match s {
                    $first_s => Ok(Self::$first),
                    $($s => Ok(Self::$variant),)*
                    other => Err($crate::UnknownLabel::new(stringify!($name), other)),
                }
            }
        }

        impl TryFrom<String> for $name {
            type Error = $crate::UnknownLabel;
            fn try_from(s: String) -> Result<Self, Self::Error> {
                s.parse()
            }
        }

        impl Default for $name {
            fn default() -> Self {
                Self::$first
            }
        }

        impl $crate::EnumLabel for $name {
            fn enum_default() -> Self {
                Self::$first
            }
            fn all_variants() -> &'static [Self] {
                &[Self::$first, $(Self::$variant),*]
            }
            fn as_str(&self) -> &'static str {
                match self {
                    Self::$first => $first_s,
                    $(Self::$variant => $s),*
                }
            }
        }
    };
}

enum_label! {
    /// Phase 1 type-safe labels (see `doc/type-safety-issues.md` §3.1 / 3.2 / 3.5 / 3.6).
    ///
    /// These are intentionally kept in `takusu-util` so that `takusu-storage`,
    /// `takusu-client`, and `takusu-worker` can all use them without changing the
    /// crate dependency graph.
    pub enum TaskStatus {
        #[default] Pending = "pending",
        Scheduled = "scheduled",
        InProgress = "in_progress",
        Completed = "completed",
        Skipped = "skipped",
    }
}

enum_label! {
    /// Filter value for task status queries.
    ///
    /// Superset of [`TaskStatus`] that adds [`TaskStatusFilter::Overdue`] — a
    /// virtual pseudo-status that selects tasks whose `end_at` has passed but
    /// are not `completed` or `skipped`. `Overdue` is never stored in the
    /// `status` column; it is expanded to a SQL predicate by storage
    /// implementations.
    pub enum TaskStatusFilter {
        #[default] Pending = "pending",
        Scheduled = "scheduled",
        InProgress = "in_progress",
        Completed = "completed",
        Skipped = "skipped",
        Overdue = "overdue",
    }
}

impl From<TaskStatus> for TaskStatusFilter {
    fn from(status: TaskStatus) -> Self {
        match status {
            TaskStatus::Pending => Self::Pending,
            TaskStatus::Scheduled => Self::Scheduled,
            TaskStatus::InProgress => Self::InProgress,
            TaskStatus::Completed => Self::Completed,
            TaskStatus::Skipped => Self::Skipped,
        }
    }
}

enum_label! {
    pub enum WindowMode {
        #[default] Day = "day",
        Period = "period",
    }
}

enum_label! {
    pub enum TokenScope {
        #[default] ReadWrite = "read-write",
        Root = "root",
    }
}

enum_label! {
    pub enum MemoryKind {
        #[default] ProperNoun = "proper_noun",
        Fact = "fact",
        TaskNote = "task_note",
    }
}

enum_label! {
    pub enum SubjectType {
        #[default] Empty = "",
        Task = "task",
        Habit = "habit",
        Skill = "skill",
        Schedule = "schedule",
    }
}

enum_label! {
    /// Phase 5 solver label (see `doc/type-safety-issues.md` §3.3).
    ///
    /// Kept in `takusu-util` because `takusu-core` does not depend on `serde`,
    /// and `takusu-storage` / `takusu-client` / `takusu-worker` all depend on `takusu-util`.
    pub enum Solver {
        #[default] Sa = "sa",
        Priority = "priority",
        Auto = "auto",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde::{Deserialize, Serialize};

    enum_label! {
        #[allow(dead_code)]
        enum Status {
            #[default] Pending = "pending",
            Scheduled = "scheduled",
            InProgress = "in_progress",
            Completed = "completed",
        }
    }

    #[test]
    fn display_round_trips_first_variant() {
        assert_eq!(Status::Pending.to_string(), "pending");
    }

    #[test]
    fn display_round_trips_other_variants() {
        assert_eq!(Status::Scheduled.to_string(), "scheduled");
        assert_eq!(Status::InProgress.to_string(), "in_progress");
        assert_eq!(Status::Completed.to_string(), "completed");
    }

    #[test]
    fn from_str_parses_known_labels() {
        assert_eq!("pending".parse::<Status>().unwrap(), Status::Pending);
        assert_eq!("scheduled".parse::<Status>().unwrap(), Status::Scheduled);
        assert_eq!("in_progress".parse::<Status>().unwrap(), Status::InProgress);
        assert_eq!("completed".parse::<Status>().unwrap(), Status::Completed);
    }

    #[test]
    fn from_str_rejects_unknown_label() {
        let err = "deleted".parse::<Status>().unwrap_err();
        assert_eq!(err.enum_name(), "Status");
        assert_eq!(err.value(), "deleted");
        assert_eq!(err.to_string(), r#"unknown Status label: "deleted""#);
    }

    #[test]
    fn try_from_string_delegates_to_from_str() {
        let s: Status = String::from("completed").try_into().unwrap();
        assert_eq!(s, Status::Completed);
    }

    #[test]
    fn try_from_string_propagates_error() {
        let err = Status::try_from(String::from("nope")).unwrap_err();
        assert_eq!(err.value(), "nope");
    }

    #[test]
    fn default_is_first_variant() {
        assert_eq!(Status::default(), Status::Pending);
    }

    #[test]
    fn enum_default_is_first_variant() {
        assert_eq!(Status::enum_default(), Status::Pending);
    }

    #[test]
    fn all_variants_lists_in_declaration_order() {
        assert_eq!(
            Status::all_variants(),
            &[
                Status::Pending,
                Status::Scheduled,
                Status::InProgress,
                Status::Completed
            ]
        );
    }

    #[test]
    fn solver_round_trips() {
        assert_eq!(Solver::Sa.to_string(), "sa");
        assert_eq!(Solver::Priority.to_string(), "priority");
        assert_eq!(Solver::Auto.to_string(), "auto");
        assert_eq!("sa".parse::<Solver>().unwrap(), Solver::Sa);
        assert_eq!("priority".parse::<Solver>().unwrap(), Solver::Priority);
        assert_eq!("auto".parse::<Solver>().unwrap(), Solver::Auto);
        assert_eq!(Solver::default(), Solver::Sa);
        assert_eq!(Solver::enum_default(), Solver::Sa);
    }

    #[derive(Debug, PartialEq, Serialize, Deserialize)]
    struct Wrapper {
        #[serde(with = "super::enum_serde")]
        status: Status,
    }

    #[derive(Debug, PartialEq, Serialize, Deserialize)]
    struct OptionWrapper {
        #[serde(with = "super::enum_serde::option", default)]
        status: Option<Status>,
    }

    #[test]
    fn serde_serializes_as_display_string() {
        let w = Wrapper {
            status: Status::InProgress,
        };
        let json = serde_json::to_string(&w).unwrap();
        assert_eq!(json, r#"{"status":"in_progress"}"#);
    }

    #[test]
    fn serde_deserializes_known_label() {
        let w: Wrapper = serde_json::from_str(r#"{"status":"completed"}"#).unwrap();
        assert_eq!(
            w,
            Wrapper {
                status: Status::Completed
            }
        );
    }

    #[test]
    fn serde_rejects_unknown_label() {
        let err = serde_json::from_str::<Wrapper>(r#"{"status":"deleted"}"#);
        assert!(err.is_err());
    }

    #[test]
    fn serde_round_trips() {
        let w = Wrapper {
            status: Status::Scheduled,
        };
        let json = serde_json::to_string(&w).unwrap();
        let back: Wrapper = serde_json::from_str(&json).unwrap();
        assert_eq!(back, w);
    }

    enum_label! {
        #[allow(dead_code)]
        pub enum Single {
            #[default] Only = "only",
        }
    }

    #[test]
    fn single_variant_works() {
        assert_eq!(Single::default(), Single::Only);
        assert_eq!(Single::all_variants(), &[Single::Only]);
        assert_eq!("only".parse::<Single>().unwrap(), Single::Only);
        assert!("nope".parse::<Single>().is_err());
    }

    enum_label! {
        #[allow(dead_code)]
        enum WithTrailingComma {
            #[default] A = "a",
            B = "b",
            C = "c",
        }
    }

    #[test]
    fn trailing_comma_is_accepted() {
        assert_eq!(WithTrailingComma::all_variants().len(), 3);
    }

    #[test]
    fn option_serde_serializes_some_as_string() {
        let w = OptionWrapper {
            status: Some(Status::InProgress),
        };
        let json = serde_json::to_string(&w).unwrap();
        assert_eq!(json, r#"{"status":"in_progress"}"#);
    }

    #[test]
    fn option_serde_serializes_none_as_null() {
        let w = OptionWrapper { status: None };
        let json = serde_json::to_string(&w).unwrap();
        assert_eq!(json, r#"{"status":null}"#);
    }

    #[test]
    fn option_serde_deserializes_known_label() {
        let w: OptionWrapper = serde_json::from_str(r#"{"status":"completed"}"#).unwrap();
        assert_eq!(
            w,
            OptionWrapper {
                status: Some(Status::Completed)
            }
        );
    }

    #[test]
    fn option_serde_deserializes_null_as_none() {
        let w: OptionWrapper = serde_json::from_str(r#"{"status":null}"#).unwrap();
        assert_eq!(w, OptionWrapper { status: None });
    }

    #[test]
    fn option_serde_deserializes_missing_as_none() {
        let w: OptionWrapper = serde_json::from_str(r#"{}"#).unwrap();
        assert_eq!(w, OptionWrapper { status: None });
    }

    #[test]
    fn option_serde_rejects_unknown_label() {
        let err = serde_json::from_str::<OptionWrapper>(r#"{"status":"deleted"}"#);
        assert!(err.is_err());
    }

    #[test]
    fn task_status_filter_from_task_status_preserves_label() {
        for status in TaskStatus::all_variants() {
            let filter: TaskStatusFilter = (*status).into();
            assert_eq!(filter.as_str(), status.as_str());
        }
    }
}
